services:
  - type: web
    name: developer-tools-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5001
    healthCheckPath: /api/tools/stats
    autoDeploy: true

